version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: monvormo
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
